/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package kutuphane.DataBase;

/**
 *
 * @author meren
 */
import javax.swing.table.DefaultTableModel;
import java.sql.SQLException;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

public class kullanıcıkitapdegerlendirme extends javax.swing.JFrame {
 private kitapDegerlendir kitapdegerlendir;
    
    public kullanıcıkitapdegerlendirme() {
         initComponents();
        this.setResizable(false);
        kitapdegerlendir= new kitapDegerlendir();
        loadKitapListToTable();
        KullanıcıManager kullanıcıManager = new KullanıcıManager();
        String loggedInUsername = kullanıcıManager.getLoggedInUsername();
        kullanıcıadı.setText(loggedInUsername);
        
    }
    private void loadKitapListToTable() {
        try {
            // Kitap listesini al
            DefaultListModel<Degerlendir> kitapListModel = kitapdegerlendir.getDegerlendirmeBooks();


            // DefaultTableModel oluştur
            DefaultTableModel tableModel = new DefaultTableModel();
            tableModel.addColumn("Kitap Adı");
            tableModel.addColumn("Değerlendirme");
            tableModel.addColumn("Puan");
            tableModel.addColumn("Kullanıcı Adı");
            

            // Kitap listesini DefaultTableModel'e ekle
            for (int i = 0; i < kitapListModel.getSize(); i++) {
                Degerlendir degerlendir = kitapListModel.get(i);
                Object[] row = {degerlendir.getKitap_adi(), degerlendir.getDegerlendirme(), degerlendir.getPuan(), degerlendir.getKullanici_adi()};
                tableModel.addRow(row);
            }

            // JTable'a DefaultTableModel'i ekle
            kitaplardegerlendirmeler.setModel(tableModel);
        } catch (SQLException e) {
            e.printStackTrace();
            // Hata durumunda gerekli işlemler yapılabilir
        }
    }
    private void loadKitapListToTable(DefaultListModel<Degerlendir> kitapListModel) {
        // DefaultTableModel oluştur
        DefaultTableModel tableModel = new DefaultTableModel();
        tableModel.addColumn("Kitap Adı");
        tableModel.addColumn("Değerlendirme");
        tableModel.addColumn("Puan");
        tableModel.addColumn("Kullanıcı Adı");
        // Kitap listesini DefaultTableModel'e ekle
        for (int i = 0; i < kitapListModel.getSize(); i++) {
            Degerlendir degerlendir = kitapListModel.get(i);
            Object[] row = {degerlendir.getKitap_adi(), degerlendir.getDegerlendirme(), degerlendir.getPuan(), degerlendir.getKullanici_adi()};
            tableModel.addRow(row);
        }
        // JTable'a DefaultTableModel'i ekle
        kitaplardegerlendirmeler.setModel(tableModel);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        kullanıcıadı = new javax.swing.JTextPane();
        anasayfa = new javax.swing.JButton();
        kitaplar = new javax.swing.JButton();
        kitapödünçal = new javax.swing.JButton();
        kitapiadeet = new javax.swing.JButton();
        kitaplarım = new javax.swing.JButton();
        kütüphanebilgileri = new javax.swing.JButton();
        çıkışyap = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        aramakutusu = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        kitaplardegerlendirmeler = new javax.swing.JTable();
        degerlendirme = new javax.swing.JTextField();
        puan = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        kitapadi = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        puanagore2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Kullanıcı Adı");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 80, 20));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kutuphane/DataBase/yeni.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 80, 70));
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, -1, -1));

        jScrollPane2.setViewportView(kullanıcıadı);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 80, -1));

        anasayfa.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        anasayfa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kutuphane/DataBase/anasayfa.png"))); // NOI18N
        anasayfa.setText("Anasayfa");
        anasayfa.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        anasayfa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anasayfaActionPerformed(evt);
            }
        });
        jPanel1.add(anasayfa, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 310, 70));

        kitaplar.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        kitaplar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kutuphane/DataBase/kitap.png"))); // NOI18N
        kitaplar.setText("Kitaplar");
        kitaplar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        kitaplar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kitaplarActionPerformed(evt);
            }
        });
        jPanel1.add(kitaplar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 310, 70));

        kitapödünçal.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        kitapödünçal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kutuphane/DataBase/ödünç al.jpg"))); // NOI18N
        kitapödünçal.setText("Kitap Ödünç Al");
        kitapödünçal.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        kitapödünçal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kitapödünçalActionPerformed(evt);
            }
        });
        jPanel1.add(kitapödünçal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 320, 70));

        kitapiadeet.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        kitapiadeet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kutuphane/DataBase/ödünçal.png"))); // NOI18N
        kitapiadeet.setText("Kitap İade Et");
        kitapiadeet.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        kitapiadeet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kitapiadeetActionPerformed(evt);
            }
        });
        jPanel1.add(kitapiadeet, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 320, 70));

        kitaplarım.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        kitaplarım.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kutuphane/DataBase/kitaplarım.png"))); // NOI18N
        kitaplarım.setText("Kitaplarım");
        kitaplarım.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        kitaplarım.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kitaplarımActionPerformed(evt);
            }
        });
        jPanel1.add(kitaplarım, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 320, 70));

        kütüphanebilgileri.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        kütüphanebilgileri.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kutuphane/DataBase/kütüphane.png"))); // NOI18N
        kütüphanebilgileri.setText("Kütüphane Bilgileri");
        kütüphanebilgileri.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        kütüphanebilgileri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kütüphanebilgileriActionPerformed(evt);
            }
        });
        jPanel1.add(kütüphanebilgileri, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 310, 70));

        çıkışyap.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        çıkışyap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kutuphane/DataBase/çıkışyap.png"))); // NOI18N
        çıkışyap.setText("Çıkış Yap");
        çıkışyap.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        çıkışyap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                çıkışyapActionPerformed(evt);
            }
        });
        jPanel1.add(çıkışyap, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 560, 310, 70));

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel9.setText("Arama Kutusu");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 140, 50));

        aramakutusu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aramakutusuActionPerformed(evt);
            }
        });
        jPanel2.add(aramakutusu, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 22, 340, 40));

        kitaplardegerlendirmeler.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kitap Adı", "Değerlendirme", "Puan", "Kullanıcı Adı"
            }
        ));
        jScrollPane1.setViewportView(kitaplardegerlendirmeler);
        if (kitaplardegerlendirmeler.getColumnModel().getColumnCount() > 0) {
            kitaplardegerlendirmeler.getColumnModel().getColumn(3).setResizable(false);
        }

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 560, 260));

        degerlendirme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                degerlendirmeActionPerformed(evt);
            }
        });
        jPanel2.add(degerlendirme, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 450, 200, 70));

        puan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));
        puan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puanActionPerformed(evt);
            }
        });
        jPanel2.add(puan, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 540, 120, 30));

        jLabel3.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel3.setText("Puan : ");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 550, -1, 20));

        kitapadi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kitapadiActionPerformed(evt);
            }
        });
        jPanel2.add(kitapadi, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 410, 120, 30));

        jLabel5.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel5.setText("Değerlendirme :");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, -1, 20));

        jButton1.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jButton1.setText("Ekle");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 580, 70, 30));

        jLabel6.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel6.setText("Eklenecek Değerlendirme");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, -1, -1));

        jLabel8.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel8.setText("Kitap Adı :");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, -1, 20));

        puanagore2.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        puanagore2.setText("Puana Göre Sırala");
        puanagore2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puanagore2ActionPerformed(evt);
            }
        });
        jPanel2.add(puanagore2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 450, 180, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aramakutusuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aramakutusuActionPerformed
        String searchKeyword = aramakutusu.getText();
        kitapDegerlendir kitapdegerlendir = new kitapDegerlendir();

    
        DefaultListModel<Degerlendir> kitapListModel = kitapdegerlendir.searchDegerlendirme(searchKeyword);

        DefaultTableModel tableModel = new DefaultTableModel();
        tableModel.addColumn("Kitap Adı");
        tableModel.addColumn("Değerlendirme");
        tableModel.addColumn("Puan");
        tableModel.addColumn("Kullanıcı Adı");
        

        for (int i = 0; i < kitapListModel.getSize(); i++) {
            Degerlendir degerlendir = kitapListModel.get(i);
            Object[] row = {degerlendir.getKitap_adi(), degerlendir.getDegerlendirme(), degerlendir.getPuan(), degerlendir.getKullanici_adi()};
            tableModel.addRow(row);
        }

        kitaplardegerlendirmeler.setModel(tableModel);
    
    }//GEN-LAST:event_aramakutusuActionPerformed

    private void puanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_puanActionPerformed

    private void degerlendirmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_degerlendirmeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_degerlendirmeActionPerformed

    private void kitapadiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kitapadiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kitapadiActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        kitapDegerlendir kitapdegerlendir = new kitapDegerlendir();
        KitapManager kitapmanager = new KitapManager();
        KullanıcıManager kullanıcıManager = new KullanıcıManager();
        String loggedInUsername = kullanıcıManager.getLoggedInUsername();
        kullanıcıadı.setText(loggedInUsername);
        String kitapAdi = kitapadi.getText().toUpperCase();
        String secilenPuan = (String) puan.getSelectedItem();
 
        

    if (kitapmanager.bookControl(kitapAdi) == 0){
    kitapdegerlendir.insertDegerlendirme(kitapadi.getText().toUpperCase(), degerlendirme.getText().toUpperCase(), secilenPuan, loggedInUsername);

    JOptionPane.showMessageDialog(null, "KİTAP EKLENDİ!");
    kitapadi.setText("");
    degerlendirme.setText("");
    puan.setSelectedIndex(0);
    kullanıcıadı.setText(loggedInUsername);
    loadKitapListToTable();
    }else{
        JOptionPane.showMessageDialog(null, "HATA: Kitap bulunamadı. Lütfen geçerli bir kitap adı girin.");
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void anasayfaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anasayfaActionPerformed
        kullanıcıanasayfa ana = new kullanıcıanasayfa();
        ana.setVisible(true);

        // Close the current frame
        this.dispose();
    }//GEN-LAST:event_anasayfaActionPerformed

    private void kitaplarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kitaplarActionPerformed
        kullanıcıkitaplar kitaplar = new kullanıcıkitaplar();
        kitaplar.setVisible(true);

        // Close the current frame
        this.dispose();
    }//GEN-LAST:event_kitaplarActionPerformed

    private void kitapödünçalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kitapödünçalActionPerformed
        kullanıcıkitapödünçal odunc = new kullanıcıkitapödünçal();
        odunc.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_kitapödünçalActionPerformed

    private void kitapiadeetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kitapiadeetActionPerformed
        kullanıcıkitapiadeet iade = new kullanıcıkitapiadeet();
        iade.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_kitapiadeetActionPerformed

    private void kitaplarımActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kitaplarımActionPerformed
        kullanıcıkitaplarım kitaplarım = new kullanıcıkitaplarım();
        kitaplarım.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_kitaplarımActionPerformed

    private void kütüphanebilgileriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kütüphanebilgileriActionPerformed
        kullanıcıkütüphanebilgileri kütüphane = new kullanıcıkütüphanebilgileri();
        kütüphane.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_kütüphanebilgileriActionPerformed

    private void çıkışyapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_çıkışyapActionPerformed
        KullanıcıManager kullanıcıManager = new KullanıcıManager();
        kullanıcıManager.removeUserFromLoginTable();
        System.exit(0);
    }//GEN-LAST:event_çıkışyapActionPerformed

    private void puanagore2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puanagore2ActionPerformed
        siralamaManager sortByRatingManager = new siralamaManager(new puanaGoreSiralama());
    kitapDegerlendir degerlendirObj = new kitapDegerlendir(sortByRatingManager);

    try {
        DefaultListModel<Degerlendir> sortedList = degerlendirObj.getSortedDegerlendirmeBooks();
        loadKitapListToTable(sortedList); // Pass the sorted list to the method
    } catch (SQLException e) {
        e.printStackTrace(); // Handle or log the exception as needed
        // Additional logic for handling the exception
    }
    }//GEN-LAST:event_puanagore2ActionPerformed
    
    
    




    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kullanıcıkitapdegerlendirme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kullanıcıkitapdegerlendirme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kullanıcıkitapdegerlendirme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kullanıcıkitapdegerlendirme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new kullanıcıkitapdegerlendirme().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton anasayfa;
    private javax.swing.JTextField aramakutusu;
    private javax.swing.JTextField degerlendirme;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField kitapadi;
    private javax.swing.JButton kitapiadeet;
    private javax.swing.JButton kitaplar;
    private javax.swing.JTable kitaplardegerlendirmeler;
    private javax.swing.JButton kitaplarım;
    private javax.swing.JButton kitapödünçal;
    private javax.swing.JTextPane kullanıcıadı;
    private javax.swing.JButton kütüphanebilgileri;
    private javax.swing.JComboBox<String> puan;
    private javax.swing.JButton puanagore2;
    private javax.swing.JButton çıkışyap;
    // End of variables declaration//GEN-END:variables
}
