

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package kutuphane.DataBase;
import java.sql.SQLException;
import javax.swing.DefaultListModel;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author meren
 */
public class kullanıcıkitaplarım extends javax.swing.JFrame {
private BorrowKitapManager borrowbookManager;
    /**
     * Creates new form adminpaneli
     */
    public kullanıcıkitaplarım() {
        initComponents();
        this.setResizable(false);
        KullanıcıManager kullanıcıManager = new KullanıcıManager();
        String loggedInUsername = kullanıcıManager.getLoggedInUsername();
        kullanıcıadı.setText(loggedInUsername);
        borrowbookManager = new BorrowKitapManager();

        loadKitapListToTable();
    }
    
    private void loadKitapListToTable() {
    try {
        // Get the logged-in username
        KullanıcıManager kullanıcıManager = new KullanıcıManager();
        String loggedInUsername = kullanıcıManager.getLoggedInUsername();

        // Get the book list from the borrowbook table
        DefaultListModel<BorrowKitap> kitapListModel = borrowbookManager.getDataBooks();

        // DefaultTableModel oluştur
        DefaultTableModel tableModel = new DefaultTableModel();
        tableModel.addColumn("Kitap Adı");
        tableModel.addColumn("Yazar Adı");
        tableModel.addColumn("Sayfa Sayısı");
        tableModel.addColumn("Türü");
        tableModel.addColumn("Kullanıcı Adı");

        // Iterate through the book list
        for (int i = 0; i < kitapListModel.getSize(); i++) {
            BorrowKitap kitap = kitapListModel.get(i);

            // Check if the username from borrowbook table matches the logged-in user in giris table
            if (isUsernameMatch(loggedInUsername, kitap.getUsername())) {
                Object[] row = {kitap.getKitapadi(), kitap.getYazar(), kitap.getSayfaSayisi(), kitap.getKategori(), kitap.getUsername()};
                tableModel.addRow(row);
            }
        }

        // JTable'a DefaultTableModel'i ekle
        kitaplarimtablosu.setModel(tableModel);
    } catch (SQLException e) {
        e.printStackTrace();
        // Hata durumunda gerekli işlemler yapılabilir
    }
}

// Method to check if usernames match
private boolean isUsernameMatch(String loggedInUsername, String bookUsername) {
    // Implement your logic to compare usernames, for example:
    return loggedInUsername.equals(bookUsername);
}



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        aramakutusu = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        kitaplarimtablosu = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        kitaplar = new javax.swing.JButton();
        çıkışyap = new javax.swing.JButton();
        anasayfa = new javax.swing.JButton();
        kitapiadeet = new javax.swing.JButton();
        kitaplarım = new javax.swing.JButton();
        kitapödünçal = new javax.swing.JButton();
        kütüphanebilgileri = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        kullanıcıadı = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Kitaplarım");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 230, 60));

        aramakutusu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aramakutusuActionPerformed(evt);
            }
        });
        jPanel2.add(aramakutusu, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 340, 40));

        jLabel9.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel9.setText("Arama Kutusu");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 140, 50));

        kitaplarimtablosu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kitap Adı", "Yazar Adı", "Sayfa Sayısı", "Türü", "Kullanıcı Adı"
            }
        ));
        jScrollPane1.setViewportView(kitaplarimtablosu);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 560, 300));

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Kullanıcı Adı");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 80, 20));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kutuphane/DataBase/yeni.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 80, 70));
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, -1, -1));

        kitaplar.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        kitaplar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kutuphane/DataBase/kitap.png"))); // NOI18N
        kitaplar.setText("Kitaplar");
        kitaplar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        kitaplar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kitaplarActionPerformed(evt);
            }
        });
        jPanel1.add(kitaplar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 310, 70));

        çıkışyap.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        çıkışyap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kutuphane/DataBase/çıkışyap.png"))); // NOI18N
        çıkışyap.setText("Çıkış Yap");
        çıkışyap.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        çıkışyap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                çıkışyapActionPerformed(evt);
            }
        });
        jPanel1.add(çıkışyap, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 560, 310, 80));

        anasayfa.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        anasayfa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kutuphane/DataBase/anasayfa.png"))); // NOI18N
        anasayfa.setText("Anasayfa");
        anasayfa.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        anasayfa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anasayfaActionPerformed(evt);
            }
        });
        jPanel1.add(anasayfa, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 310, 70));

        kitapiadeet.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        kitapiadeet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kutuphane/DataBase/ödünçal.png"))); // NOI18N
        kitapiadeet.setText("Kitap İade Et");
        kitapiadeet.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        kitapiadeet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kitapiadeetActionPerformed(evt);
            }
        });
        jPanel1.add(kitapiadeet, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 320, 70));

        kitaplarım.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        kitaplarım.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kutuphane/DataBase/kitaplarım.png"))); // NOI18N
        kitaplarım.setText("Kitaplarım");
        kitaplarım.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        kitaplarım.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kitaplarımActionPerformed(evt);
            }
        });
        jPanel1.add(kitaplarım, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 320, 70));

        kitapödünçal.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        kitapödünçal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kutuphane/DataBase/ödünç al.jpg"))); // NOI18N
        kitapödünçal.setText("Kitap Ödünç Al");
        kitapödünçal.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        kitapödünçal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kitapödünçalActionPerformed(evt);
            }
        });
        jPanel1.add(kitapödünçal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 320, 70));

        kütüphanebilgileri.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        kütüphanebilgileri.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kutuphane/DataBase/kütüphane.png"))); // NOI18N
        kütüphanebilgileri.setText("Kütüphane Bilgileri");
        kütüphanebilgileri.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        kütüphanebilgileri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kütüphanebilgileriActionPerformed(evt);
            }
        });
        jPanel1.add(kütüphanebilgileri, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 310, 70));

        jScrollPane2.setViewportView(kullanıcıadı);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 80, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kitaplarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kitaplarActionPerformed
        kullanıcıkitaplar kitaplarFrame = new kullanıcıkitaplar();
        kitaplarFrame.setVisible(true);

    // Close the current frame
        this.dispose();
    }//GEN-LAST:event_kitaplarActionPerformed

    private void çıkışyapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_çıkışyapActionPerformed
         KullanıcıManager kullanıcıManager = new KullanıcıManager();
        kullanıcıManager.removeUserFromLoginTable();
        System.exit(0);
    }//GEN-LAST:event_çıkışyapActionPerformed

    private void anasayfaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anasayfaActionPerformed
        kullanıcıanasayfa anasayfa = new kullanıcıanasayfa();
        anasayfa.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_anasayfaActionPerformed

    private void kitapiadeetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kitapiadeetActionPerformed
        kullanıcıkitapiadeet iade = new kullanıcıkitapiadeet();
        iade.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_kitapiadeetActionPerformed

    private void kitaplarımActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kitaplarımActionPerformed
        
    }//GEN-LAST:event_kitaplarımActionPerformed

    private void kitapödünçalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kitapödünçalActionPerformed
        kullanıcıkitapödünçal odunc = new kullanıcıkitapödünçal();
        odunc.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_kitapödünçalActionPerformed

    private void kütüphanebilgileriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kütüphanebilgileriActionPerformed
       kullanıcıkütüphanebilgileri kütüphane = new kullanıcıkütüphanebilgileri();
        kütüphane.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_kütüphanebilgileriActionPerformed

    private void aramakutusuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aramakutusuActionPerformed
        KullanıcıManager kullanıcıManager = new KullanıcıManager();
        String loggedInUsername = kullanıcıManager.getLoggedInUsername();
        String searchKeyword = aramakutusu.getText();
        BorrowKitapManager kitapManager = new BorrowKitapManager();

    
        DefaultListModel<BorrowKitap> kitapListModel = kitapManager.searchBooks(searchKeyword);

        DefaultTableModel tableModel = new DefaultTableModel();
        tableModel.addColumn("Kitap Adı");
        tableModel.addColumn("Yazar Adı");
        tableModel.addColumn("Sayfa Sayısı");
        tableModel.addColumn("Türü");
        tableModel.addColumn("Kullanıcıadı");

        for (int i = 0; i < kitapListModel.getSize(); i++) {
            BorrowKitap kitap = kitapListModel.get(i);

            // Check if the username from borrowbook table matches the logged-in user in giris table
            if (isUsernameMatch(loggedInUsername, kitap.getUsername())) {
                Object[] row = {kitap.getKitapadi(), kitap.getYazar(), kitap.getSayfaSayisi(), kitap.getKategori(), kitap.getUsername()};
                tableModel.addRow(row);
            }
        }

        kitaplarimtablosu.setModel(tableModel);
        
        
    }//GEN-LAST:event_aramakutusuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kullanıcıkitaplarım.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kullanıcıkitaplarım.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kullanıcıkitaplarım.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kullanıcıkitaplarım.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new kullanıcıkitaplarım().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton anasayfa;
    private javax.swing.JTextField aramakutusu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton kitapiadeet;
    private javax.swing.JButton kitaplar;
    private javax.swing.JTable kitaplarimtablosu;
    private javax.swing.JButton kitaplarım;
    private javax.swing.JButton kitapödünçal;
    private javax.swing.JTextPane kullanıcıadı;
    private javax.swing.JButton kütüphanebilgileri;
    private javax.swing.JButton çıkışyap;
    // End of variables declaration//GEN-END:variables
}
